name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            vagnernasc88/broker-ms:latest
            vagnernasc88/broker-ms:${{github.run_number}}.0.0
